---
- name: Update apt cache.
  apt: 
    update_cache: yes 
    cache_valid_time: 86400

- name: Install Omeka dependencies
  apt: 
    name: "{{ item }}"
    state: installed
  with_items:
    - apache2
    - php5
    - libapache2-mod-php5
    - php5-mysql
    - imagemagick


